fga-eps-mds/2020.1-stay-safe-user-service

docker-compose.yml
requirements.txt
src/controllers/auth.py
src/main.py
src/settings.py
src/tests/test_auth.py
src/views/auth.py

Adding authentication user
$ sudo docker-compose run api pytest

3 user authentication

---

.gitignore
requirements.txt
src/controllers/auth.py
src/controllers/occurrence.py
src/controllers/user.py
src/database/models.py
src/settings.py
src/tests/test_auth.py
src/tests/test_occurrence.py
src/tests/test_user.py
src/utils/validators/general.py
src/views/auth.py
src/views/occurrence.py
src/views/user.py

Resolves #6 
Adds encryption to the user's password and authentication at the required endpoints
```$ sudo docker-compose run api pytest ```

Protect user

---

.gitignore
src/controllers/neighborhood.py
src/controllers/rating.py
src/database/models.py
src/main.py
src/tests/mock_ratings.py
src/tests/test_rating.py
src/utils/validators/general.py
src/utils/validators/rating.py
src/views/neighborhood.py
src/views/rating.py

#7 
Create the neighborhood rating's CRUD.

Create the neighborhood rating crud

---

requirements.txt
src/controllers/rating.py
src/database/db.py
src/main.py
src/static/swagger.json

Resolve #11
Configure the swagger and add and describe the existing endpoints
Go to the api/docs endpoint

Swagger configuration

---

src/controllers/occurrence.py
src/controllers/rating.py
src/database/db.py
src/database/models.py
src/tests/test_occurrence.py
src/utils/validators/occurrence.py
src/views/occurrence.py
src/views/rating.py

Resolves #14 
Implements the filter to capture all occurrences and all classifications of a specific user in the respective "get all" endpoints and hide the user's name in the occurrence get
The function that implements the filtering in the database is not generic, it is accepting only the user filter. In the future, implement it in a way that accepts more parameters
Make a get on endpoits /api/rating?user=username and /api/occurrences/?user=username.
Check that the occurrences are coming without displaying the username
Run the tests:
```
$ docker-compose run api pytest
```

Filter to occurrences and all classifications of a user

---

README.md
requirements.txt
src/.pylintrc
src/controllers/auth.py
src/controllers/neighborhood.py
src/controllers/rating.py
src/controllers/user.py
src/database/db.py
src/database/models.py
src/tests/test_auth.py
src/tests/test_rating.py
src/utils/formatters.py
src/views/neighborhood.py

Resolves #12 
Setup all steps of pipeline.
Follow the README.md to run pylint and pytest

12 pipeline config

---

src/controllers/occurrence.py
src/tests/test_occurrence.py

Corrects the return of the occurrence after being updated so that it comes without the user's name and corrects the respective test
Update an occurrence and verify that the response is coming without the username
Run the tests:
```
$ sudo docker-compose run api pytest
```

Fix update occurrence

---

README.md
requirements.txt

Resolves #26 
Added coverage to requirements and updated readme with the commands to run coverage.
Run ```docker-compose run api coverage run -m pytest``` and then ```docker-compose run api coverage report -m```

Added coverage and updated readme

---

src/controllers/occurrence.py
src/controllers/rating.py
src/database/db.py
src/database/models.py
src/static/swagger.json
src/tests/mock_occurrences.py
src/tests/test_occurrence.py
src/tests/test_rating.py
src/utils/validators/occurrence.py
src/views/occurrence.py

Resolves #28 
Creates the occurrence_type query param om get_all occurrences route. If it has more than one occurrence_type it has to be separated with ',', with spaces or not, like that: _?occurrence_type=Furto a Transeunte, Latrocínio_. It also update the types of occurrences, adding two more: "Furto a Transeunte" and "Furto de Veículo".
To make the route better it would be good to pass two query params. In this case it would be user and occurrence_type. Now it can only pass one of them. If passes both the route returns all the occurrences from an user.
Run the tests: docker-compose run api pytest
Make a GET request on /occurrences passing the query param occurrence_type. Ex.: /occurrences?occurrence_type=Roubo de Veículo, Roubo a Transeunte and check if the occurrences that returned it …

Creates the occurrence_type filter for get_all occurrences route

---

src/controllers/auth.py
src/tests/test_auth.py
src/views/auth.py

Resolves #33 
Resolves the error that occurs when authentication is not passed on the api/auth endpoint. The error is best described in the issue. It was resolved by checking for authorization and returning an error message if you have not.
Make a request at the endpoint /api/auth without providing authentication and verify that the error has been resolved

Checks if auth was passed in the request

---

src/controllers/neighborhood.py
src/controllers/rating.py
src/static/swagger.json
src/tests/mock_neighborhood.py
src/tests/mock_ratings.py
src/tests/test_neighborhood.py
src/tests/test_rating.py
src/utils/neighborhood_statistics.py
src/views/neighborhood.py
src/views/occurrence.py
src/views/rating.py

Resolves #31 
This PR calculates the statistics requested on the issue for the get one neighborhood route. It returns as attributes of the object returned. The attributes are 'average', 'lighting', 'movement' and 'police'.
This PR also created a new query param on get all ratings route. The param is 'neighborhood' and receives the id of the neighborhood that you want to get all the ratings from.
1) Run the tests: docker-compose run api pytest
2) Create a neighborhood or uses the script to create all the neighborhoods, but this may take a while
3) Create a few ratings for the neighborhood that was created
4) Make a GET request on /neighborhood/<id_neighborhood>
5) See the statistics

Calculate the neighborhoods' statistics

---

README.md
src/controllers/neighborhood.py
src/database/db.py
src/static/save_on_db.py
src/static/swagger.json
src/tests/test_neighborhood.py
src/tests/test_rating.py
src/views/neighborhood.py

Resolves #40 
This PR created the filters city and state for get all neighborhoods route. Both filter must be passed together and the state has to be just the UF. The name of the city must be with all caracteres, special or not, and spaces correctly.
1) sudo docker-compose up
2) sudo docker-compose exec api pytest
3) Make a GET request passing the filters to /neighborhoods.
Ex.: /neighborhoods?city=Águas Claras&state=DF.
Obs.: If you don't have the neighborhoods already in your machine got to the folder src/static and run python3 save_on_db.py. This may take a while because SP has a lot of neighborhoods, but if you just want to save the neighborhoods on DF, because it is so much fast, comment from line 25 to 34 on save_on_db.py.

Create filters for get all neighborhoods

---

requirements.txt
src/controllers/neighborhood.py
src/controllers/rating.py
src/database/db.py
src/database/models.py
src/static/save_on_db.py
src/static/swagger.json
src/tests/mocks/mock_ratings.py
src/tests/test_neighborhood.py
src/tests/test_rating.py
src/utils/neighborhood_statistics.py
src/utils/validators/rating.py
src/views/occurrence.py
src/views/rating.py

Resolves #37 
This PR changes the rating model to a more scalable one. Now the details is a composite type attribute that has the details inside. Now the possible details are lighting, movement_of_people and police_rounds.
Run the tests
Tests the rating crud manually and the get neighborhoods routes and check if the statistics are correct.

Change rating model

---

.gitignore
README.md

Resolves #54 
Added the instructions of how to run the Sonarqube Scan to analize the code of the repository.
Run
1. Run the sonarqube server with ```docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest```
2. Run the code scan with ```docker run -ti -v $(pwd):/usr/src --link sonarqube newtmitch/sonar-scanner -Dsonar.projectName="User Service" -Dsonar.projectKey=userservice```
3. See the results of the scan in http://localhost:9000/projects

54 sonarqube

---

src/controllers/occurrence.py
src/controllers/rating.py
src/database/db.py
src/static/save_on_db.py
src/tests/mocks/mock_occurrences.py
src/tests/test_occurrence.py
src/tests/test_user.py
src/utils/validators/occurrence.py
src/utils/validators/rating.py
src/utils/validators/user.py

Resolves #50 
This PR implements the business rules discussed in issue #50
1) Try to create more than 5 occurrences within 7 days
2) Try to edit an occurrence that is 3 months old*
3) Try to get all occurrences and check if it returned one that is 1 year old*
*To check that you have to update the occurrence_date_time of some occurrences. To do this update the fields on occurrence_controller.update and add occurrence_date_time. You may need to comment the function that does the validation. Pass the json with a date like "2019-01-01 10:10:10" that is more than 1 year old and check the steps above.

Implement some business rules

---

src/controllers/favorite_places.py
src/database/models.py
src/static/swagger.json
src/tests/mocks/mock_favorite_places.py
src/tests/test_favorite_places.py
src/utils/validators/favorite_places.py

Resolves #49 
Added the name field to the favorite location model
Run the tests and try to create a favorite place with the name field.

Add name to favorite place

---

requirements.txt
src/controllers/favorite_places.py
src/controllers/occurrence.py
src/controllers/rating.py
src/controllers/user.py
src/database/db.py
src/database/models.py
src/tests/mocks/mock_users.py
src/tests/test_neighborhood.py
src/tests/test_occurrence.py
src/utils/notifications.py
src/utils/validators/user.py

Resolves #56 
Adds the two necessary columns to user table.
Updating a user with ```device_token: "your token here"``` being passed on body

Add push notification fields to user

---

src/controllers/auth.py
src/controllers/favorite_places.py
src/controllers/occurrence.py
src/controllers/rating.py
src/database/db.py
src/static/swagger.json
src/tests/test_auth.py
src/tests/test_favorite_places.py
src/tests/test_neighborhood.py
src/tests/test_occurrence.py
src/tests/test_rating.py
src/tests/test_user.py
src/utils/validators/occurrence.py
src/utils/validators/rating.py
src/utils/validators/user.py

Resolves #60 
The correction handles the duplication error before presenting it to the user.
Try to register a user with an existing username or email.

Improve return messages

---

src/database/models.py
src/static/swagger.json
src/utils/validators/occurrence.py

Resolves #61 
Changes the name of occurrence types "Roubo a Transeunte" and "Furto a Transeunte" to "Roubo a Pedestre" and "Furto a Transeunte".
1) Try to create an occurrence with "Roubo a Transeunte" and see that it fails
2) Create an occurrence with "Roubo a Pedestre" and see if it was created successfully

Changing names of occurrence types

---

src/controllers/notifications.py
src/database/models.py
src/main.py
src/static/swagger.json
src/tests/mocks/mock_users.py
src/utils/utils.py
src/views/notifications.py

Resolves #65
This PR creates the notification system for occurrences reported near favorite places so when an user reports an occurrence near some favorite place the owner of this favorite place will be notified. 
1) Get the expo token by signin/signup on application frontend. You have to run the frontend to obtain this
2) After this make a GET to your user on insomnia/postman and see the expo token there to confirm
3) Create a favorite place with a second user, this user does not have to obtains the expo token, we left a example below:
```
{
"id_place": 1,
"latitude": -15.833975,
"longitude": -47.91599,
"name": "minha casa",
"user": "lboaventura25"
}
```
4) Create an occurrence with the main user, we left a example below:
```
{
"gun": "Fire",
"location": [
-15.833975,
-47.91597
], …
```

Created the notification system for occurrences reported near favorite places
